name: ranjith

on:
    push:
        branches:
            - main
            - master
jobs:
    ranjith:
        runs-on: ubuntu-latest
        steps:
            - name: welcome
              run: |
                ec "hello"
                ec "hello " > welcome.txt
    kumer:
        if: ${{ failure() }}
        runs-on: ubuntu-latest
        steps:
            - name: actions
              run: echo "hello world"